sudo: required # docker requires superuser creds
services:
    - docker #ask travis to hv docker running
before_install: #cmds before tests r run or deployment happens
    - docker build -t docker-react -f Dockerfile.dev .
script:
    # watches for exit codes. if not 0 then build fails
    - docker run -e CI=true docker-react npm run test
language: generic 
deploy: 
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react" #name of app on EBS
    env: "DoverReact-env" #EBS app env
    bucket_name: elasticbeanstalk-us-west-2-719317498042
    bucket_path: "docker-react" #folder equal to appname on s3
    on:
        branch: master #deploy on branch master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"