# ver of docker-compose
version: '3'
services:
    react-app:
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            # dash is array
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        #stdin_open: true
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev       
        volumes:
            - .:/app
            - /app/node_modules
        command: ["npm", "run", "test"]
 
#web:
  #stdin_open: true